config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { sessions: 'users/sessions',
                            registrations: 'users/registrations' }

  root 'static_pages#home'

  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  namespace :admin do
    resources :users
    resources :hotels

    root to: 'users#index'
  end

  namespace :api do
    namespace :v1 do
      devise_for :users

      resources :hotels
      resources :reviews, only: [:create]

      post '/rate' => 'rater#create', :as => 'rate'

    end
  end

  resources :users, only: [:show]
  resources :hotels
  resources :reviews, only: [:create]

  post '/rate' => 'rater#create', :as => 'rate'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  default_scope -> { order('hotels.created_at DESC') }
  scope :approved, -> { where(status: 'approved') }
  scope :for_owner, -> (user_id) { find_by_user_id(user_id) }
  scope :sorted_by, -> (field, value) { reorder("hotels.#{field} #{value}") }
  scope :max_price_for_room, -> { approved.maximum :price_for_room }
  scope :with_best_rate, -> { includes(:best_rate) }
  scope :rated, -> { includes(:title_average) }
  scope :rated_and_filtered, -> (filters) { rated.where(filters) }
  scope :rated_top, -> (top_count) {
    joins(:title_average).reorder('rating_caches.avg DESC').limit(top_count)
  }

  belongs_to :user
  has_one :best_rate,
          -> { with_rater.with_review },
          class_name: 'Rate', foreign_key: :rateable_id

  validates :title, presence: true,
            length: { maximum: 50 }
  validates :address, presence: true,
            length: { maximum: 75 }
  validates :price_for_room, presence: true,
            numericality: { greater_than: 0 }

  before_save :pending_status

  paginates_per 9
  resourcify
  ratyrate_rateable 'title'
  mount_base64_uploader :photo,
                        PhotoUploader,
                        file_name: -> (u) { u.title }

  private
    def pending_status
      self.status = 'pending'
    end
end

app/controllers/admin/hotels_controller.rb
module Admin
  class HotelsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Hotel.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Hotel.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v1/hotels_controller.rb
class Api::V1::HotelsController < ApiController
  before_action :authenticate_by_token, except: [:index, :show]
  before_action :find, except: [:index, :create]
  before_action :owner, only: [:update, :destroy]
  before_action :prepare_hotels, only: [:index]

  respond_to :json

  def index
    if @hotels.nil? || !@hotels.any?
      @error_message = 'No hotels was found by request'
      render json: @error_message, status: :not_found
    else
      render json: @hotels, each_serializer: HotelCollectionSerializer, status: :ok
    end
  end

  def show
    render json: @hotel, serializer: HotelSerializer, status: :ok
  end

  def create
    params[:user_id] = @user.id
    @hotel = Hotel.new(permitted_params)
    if @hotel.save
      @message = 'Record was created'
      render json: @message, status: :created
    else
      @error_message = @hotel.errors.messages
      render json: @error_messages , status: :bad_request
    end
  end

  def update
    if @hotel.update_attributes(permitted_params)
      @message = 'Record was updated'
      render json: @message, status: :ok
    else
      @error_message = @hotel.errors.messages
      render json: @error_messages , status: :bad_request
    end
  end

  def destroy
    @hotel.destroy
    @message = 'Record was deleted'
    render json: @message, status: :ok
  end

  private
    def find
      @hotel = Hotel.where(id: params[:id]).first
      if @hotel.nil?
        @error_message = 'Record was not found'
        render json: @error_message, status: :not_found
      end
    end

    def owner
      if @user.id != @hotel.user_id
        @error_message = 'Record belongs to another user'
        render json: @error_message, status: :forbidden
      end
    end

    def permitted_params
      params.permit(:wifi_included, :breakfast_included,
                    :room_description, :price_for_room,
                    :title, :address, :photo, :user_id)
    end

    def prepare_hotels
      check_filters
      return filtered if @filters.any?
      return for_owner if params[:user_id]
      return top if params[:top_count]
      params[:page_num] ||= 1
      params[:page_size] ||= @_default_per_page
      @hotels = Hotel.rated.page(params[:page_num]).per(params[:page_size])
    end

    def top
      @hotels = Hotel.rated_top(params[:top_count])
    end

    def for_owner
      @hotels = Hotel.rated.find_by_user_id(params[:user_id])
    end

    def filtered
      @hotels = Hotel.rated_and_filtered(@filters)
    end

    def check_filters
      @filters = {}
      params.each do |key, value|
        case key
          when 'title'
            @filters[:title] = value
          when 'address'
            @filters[:address] = value
          when 'star_rating'
            Rails.logger.info("INFO " + value)
            @filters[:star_rating] = mto_a(value)
          when 'user_rating'
            @filters[:rating_caches] = { avg: to_r(value) }
          when 'breakfast_included'
            @filters[:breakfast_included] = value
          when 'wifi_included'
            @filters[:wifi_included] = value
        end
      end
    end

    def mto_a(string)
      array = string.tr('[]','').split(',').map{|c| c.to_i}
      array
    end

    def to_r(string)
      range = string.split('..').map{|c| c.to_i}
      range[0]..range[1]
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :find, :except => [:index, :new]
  before_action :owner, :only => [:edit, :update, :destroy]


  def index
    page_num = params[:page] || 1
    @hotels = Hotel.rated.with_best_rate.page(page_num)
  end

  def show
    if user_signed_in?
      @rating = Rate.find_by_rater_id_and_rateable_id current_user.id, @hotel.id
    end
    unless @rating.nil?
      @review = @rating.review || @rating.build_review
    end

    # @reviews = Rate.where(rateable_id: @hotel.id);
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(permitted_params)

    if @hotel.save
      redirect_to hotels_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @hotel.update_attributes(permitted_params)
      redirect_to hotels_path
    else
      render :edit
    end
  end

  def destroy
    @hotel.destroy

    redirect_to hotels_path
  end

  private

    def find
      @hotel = Hotel.find(params[:id])
    end

    def permitted_params
      params.require(:hotel).permit(:wifi_included, :breakfast_included,
                                    :room_description, :price_for_room,
                                    :title, :address, :photo, :user_id)
    end

    def owner
      if current_user.id != @hotel.user_id
        flash[:danger] = 'У вас нет доступа к чужим записям'
        redirect_to root_path
      end
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
  def score_to_s(score)
    case score.round
      when 0..2
        'Очень плохо'
      when 3..4
        'Плохо'
      when 5..6
        'Нормально'
      when 7..8
        'Хорошо'
      when 9..10
        'Очень хорошо'
    end
  end

  def my_image_url(hotel)
    default_image = 'default.png'
    if hotel.photo
      hotel.photo.url
    else
      default_image
    end
  end
end

app/views/hotels/_hotel.html.haml
.card
  - if hotel.photo?
    %a{href: hotel_path(hotel)}
      = image_tag hotel.photo.url, class: 'card-image'
  - else
    %a{href: hotel_path(hotel)}
      = image_tag 'default.png', class: 'card-image'
  .card-block
    .main.bottom-line-border
      %p.title
        = link_to hotel.title, hotel_path(hotel)
      - if hotel.title_average
        %p.score
          = "#{number_with_precision(hotel.title_average.avg, precision: 1)} #{score_to_s hotel.title_average.avg}"
        %p.score.rater-count
          = "Основано на оценках: #{hotel.title_average.qty}"
      - else
        %p.score
          Оценки пока отсутствуют
      %p.star_rating
        - hotel.star_rating.times do
          %i.glyphicon.glyphicon-star
    - if hotel.best_rate
      .best_review
        - if hotel.best_rate.text.length < 150
          %p.text-preview
            Большой текст текст текст текст текст текст текст текст
            текст текст текст текст текст текст текст текст текст
            текст текст текст...
          %p.text-full
            Большой текст текст текст текст текст текст текст текст
            текст текст текст текст текст текст текст текст текст
            текст текст  текст текст текст текст текст текст текст
            текст текст текст текст текст текст текст текст текст
            текст текст  текст текст текст текст текст текст текст
            текст текст текст текст текст текст текст текст текст
            текст текст текст
          .center
            %button.full-text-btn
              Показать больше
              %i.glyphicon.glyphicon-triangle-bottom
        - else
          %p.text-full
            Большой текст текст текст текст текст текст текст текст
            текст текст текст текст
          -# Если длина больше 150 символов - то скрываем остальное + кнопка "Показать больше"
        %p.author
          = hotel.best_rate.author_full_name
    -#%p
    -#  = link_to 'Просмотреть', hotel_path(hotel)
    -#  - if user_signed_in? && hotel.user_id == current_user.id
    -#    = link_to 'Редактировать', edit_hotel_path(hotel)

app/views/hotels/edit.html.haml
%h1 Редактирование записи
= simple_form_for @hotel, :html => { :multipart => true } do |f|
  = f.error_notification
  = f.hidden_field :id
  = f.hidden_field :user_id, :value => current_user.id
  = f.input :title, label: 'Название', required: true, autofocus: true,
              placeholder: 'Вспомните название отеля'
  = f.input :address, label: 'Адрес', required: true,
              placeholder: 'Адрес бы тоже не помешал'
  = f.input :room_description, label: 'Описание комнаты', as: :text, required: true,
              :input_html => { rows: '5' }, placeholder: 'Hotel description'
  = f.input :price_for_room, label: 'Цена за сутки', required: true,
              placeholder: 'Только честно'
  = f.input :breakfast_included, label: 'Есть завтрак',
              as: :boolean
  = f.input :wifi_included, label: 'Есть wi-fi',
                as: :boolean
  = f.file_field :photo, label: 'Изображение', id: 'image_load'
  = f.hidden_field :photo_cache
  - if @hotel.photo?
    = image_tag(@hotel.photo_url, :id => 'image_show')
  - else
    %img#image_show
  = f.button :submit, 'Сохранить', class: 'btn btn-success btn-lg'
  = link_to 'Назад', url_for(:back), class: 'btn btn-lg'

app/views/hotels/index.html.haml
= provide :title, 'Hotels'
= render 'layouts/big_search_form'

%h3.my-panel-title
  Найдите подходящий вариант и отправляйтесь!
- if @hotels.any?
  .top-pagination-group
    = paginate @hotels
  .card-list
    - @hotels.each do |hotel|
      = render hotel
  .bottom-pagination-group
    = paginate @hotels
- else
  %p Удивительное рядом

app/views/hotels/new.html.haml
%h1 Новая запись
= simple_form_for @hotel, :html => { :multipart => true } do |f|
  = f.error_notification
  = f.hidden_field :user_id, :value => current_user.id
  = f.input :title, label: 'Название', required: true, autofocus: true,
              placeholder: 'Вспомните название отеля'
  = f.input :address, label: 'Адрес', required: true,
              placeholder: 'Адрес бы тоже не помешал'
  = f.input :room_description, label: 'Описание комнаты', as: :text, required: true,
              :input_html => { rows: '5' }, placeholder: 'Hotel description'
  = f.input :price_for_room, label: 'Цена за сутки', required: true,
              placeholder: 'Только честно'
  = f.input :breakfast_included, label: 'Есть завтрак',
              as: :boolean
  = f.input :wifi_included, label: 'Есть wi-fi',
                as: :boolean
  = f.file_field :photo, label: 'Изображение', id: 'image_load'
  = f.hidden_field :photo_cache
  - if @hotel.photo?
    = image_tag(@hotel.photo_url, :id => 'image_show')
  - else
    %img#image_show
  = f.button :submit, 'Сохранить', class: 'btn btn-success btn-lg'
  = link_to 'Назад', hotels_path, class: 'btn btn-lg'

app/views/hotels/show.html.haml
= render 'layouts/small_search_form'

.hotel-show-body
  .hotel-show-head
    .hotel-left
      %p.hotel-title
        = @hotel.title
        - @hotel.star_rating.times do
          %i.glyphicon.glyphicon-star.star_rating
      %p.hotel-address
        = @hotel.address
    .hotel-right
      - if @hotel.title_average
        .hotel-rating
          = score_to_s @hotel.title_average.avg
          .hotel-score
            = number_with_precision(@hotel.title_average.avg, precision: 1)
        %p.hotel-rater-count
          = "Основано на оценках: #{@hotel.title_average.qty}"
      - else
        %p.hotel-rating
          Оценки пока отсутствуют
  .hotel-content.bottom-line-border
    .row
      .col-xs-8
        - if @hotel.photo?
          = image_tag @hotel.photo.medium.url
        - else
          = image_tag 'default.png'
      .col-xs-4.hotel-description
        %h3 Описание
        %p
          = @hotel.room_description

  .hotel-includes.bottom-line-border
    .include-title
      %h4
        Особенности:
    .include-item
      %i.glyphicon.glyphicon-cutlery{class: "include-#{@hotel.breakfast_included}"}
      %p Наличие завтрака
    .include-item
      %i.glyphicon.glyphicon-signal{class: "include-#{@hotel.wifi_included}"}
      %p Бесплатный wi-fi
  - if @rating
    = render 'reviews/review'
  .hotel-reviews
    %h4 Отзывы проверенных посетителей


  = link_to 'К отелям', hotels_path, class: 'btn my-btn'
  = link_to 'Вверх', '#', class: 'btn my-btn'