config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { sessions: 'users/sessions',
                            registrations: 'users/registrations' }

  root 'static_pages#home'

  match '/home', to: 'static_pages#home', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  namespace :admin do
    resources :users
    resources :hotels

    root to: 'users#index'
  end

  namespace :api do
    namespace :v1 do
      devise_for :users

      resources :hotels
      resources :reviews, only: [:create]

      post '/rate' => 'rater#create', :as => 'rate'

    end
  end

  resources :users, only: [:show]
  resources :hotels
  resources :reviews, only: [:create]

  post '/rate' => 'rater#create', :as => 'rate'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_big_search_form.html.haml
.big-search-banner
  .title
    %h1 НАЧНИТЕ СВОЁ ПУТЕШЕСТВИЕ ЗДЕСЬ!
    %h4
      Ищите, просматривайте информацию об отелях, читайте отзывы
      и участвуйте в формировании рейтинга
  .panel.panel-search
    .panel-body
      = simple_form_for :filter, url: '#' do |f|
        .bottom-line-border
          #common.row
            .col-xs-12
              .input-text
                = f.label :name, 'Название:'
                = f.input :name, required: false, label: false,
                                  placeholder: 'Помните название?'
              .input-text
                = f.label :address, 'Адрес:'
                = f.input :address, required: false, label: false,
                                     placeholder: 'Знаете адрес?'
              = f.button :submit, 'Начать поиск', class: 'search-btn'
          #details.row
            .col-xs-10
              .input-number
                = f.label :star_rating, 'Количество звёзд:'
                = f.hidden_field :star_rating
                #stars.starrr
              .input-range
                = f.label :user_rating, 'Оценка пользователей:'
                = f.hidden_field :user_rating
                %div
                  %input#rating.span2{'data-slider-max' => 10, 'data-slider-min' => 1,
                                      'data-slider-step' => 0.5, 'data-slider-value' => [4,7],
                                      'data-slider-id' => 'rating', type: 'text', value: ''}/
              .input-range
                = f.label :price, 'Цена:'
                = f.hidden_field :price
                %div
                  %input#price.span2{'data-slider-max' => 450, 'data-slider-min' => 10,
                                     'data-slider-step' => 10, 'data-slider-value' => [50,400],
                                     'data-slider-id' => 'price', type: 'text', value: ''}/
              .input-checkbox
                = f.input :breakfast, as: :boolean, required: false,
                                      label: 'Завтрак'
              .input-checkbox
                = f.input :wifi, as: :boolean, required: false,
                                 label: 'Wi-Fi'
      .center
        %button#details-btn
          Уточните ваш поиск
          %i.glyphicon.glyphicon-triangle-bottom

app/views/layouts/_footer.html.haml
%footer
  .row
    .site-info.col-xs-4
      %h4 Hotel Advisor
      %p
        Сайт для поиска и оценки отелей, посещаемых пользователями.
        Так же содержит новостные материалы, связанные с туризмом
      %p
        Copyright © 2017 Hotel Advisor.
        %br
        Все права защищены
    .info-links.col-xs-4
      %h4 Рекомендуем посетить:
      %nav
        %ul.nav
          %li
            = link_to 'Помощь', help_path
          %li
            = link_to 'О нас', about_path
          %li
            = link_to 'Контакты', contact_path

app/views/layouts/_header.html.haml
%header.navbar
  .container-fluid
    %nav.collapse.navbar-collapse
      #logo.navbar-header
        %a.navbar-brand{ href: root_path}
          = image_tag 'logo.jpg'
      %ul.nav.navbar-nav.navbar-right
        %li.right-line-border
          = link_to 'Главная', home_path
        %li.right-line-border
          = link_to 'Отели', hotels_path
        %li
          = link_to 'Новости', '#'
        - if user_signed_in?
          %li.dropdown
            %a#btn-logout.dropdown-toggle.btn{ 'aria-expanded' => false, 'aria-haspopup' => true,
                                               'data-toggle' => 'dropdown', href: '#', role: 'button' }
              Аккаунт
              %i.glyphicon.glyphicon-triangle-bottom
            %ul#account-menu.dropdown-menu
              %li
                = link_to 'Профиль', user_path(current_user)
              %li
                = link_to 'Настройки', edit_user_registration_path
              %li.divider{ role: 'separator' }
              %li
                = link_to 'Выйти', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Войти', new_user_session_path,
                               class: 'btn', id: 'btn-login'
          %li
            = link_to 'Зарегистрироваться', new_user_registration_path,
                                            class: 'btn', id: 'btn-register'

app/views/layouts/_small_search_form.html.haml
.small-search-banner
  = simple_form_for :filter, url: '#' do |f|
    #common.row
      .col-xs-12
        .input-text
          = f.input :name, required: false, label: false,
                                  placeholder: 'Помните название?'
        .input-text
          = f.input :address, required: false, label: false,
                                     placeholder: 'Знаете адрес?'
        = f.button :submit, 'Начать поиск', class: 'search-btn'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield :title)
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body

    = render 'layouts/header'

    = yield

    = render 'layouts/footer'

    .flash-messages
      - flash.each do |key, value|
        %div{class: "alert alert-#{key}", role: 'alert'}
          - case key
          - when 'success'
            %i.glyphicon.glyphicon-ok-sign
          - when 'danger'
            %i.glyphicon.glyphicon-remove-sign
          - when 'info'
            %i.glyphicon.glyphicon-info-sign
          - when 'warning'
            %i.glyphicon.glyphicon-exclamation-sign
          = value

    = debug(params) if Rails.env.development?